[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[[redirects]]
  from = "/share-target"
  to = "/.netlify/functions/share-target"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false

[functions]
  node_bundler = "esbuild"
